site_name: UBEATZ
site_url: https://ubeatz.indosoft.co.id
# theme : readthedocs
theme : 
    name : material
    features : 
      - search.suggest
      - search.highlight
      - content.tabs.link
plugins: 
    - search
    - glightbox
# markdown_extensions:
#     - attr_list
#     - md_in_html
nav:
    - Home : "index.md"
    - Version :
      - Latest Version : "version/check_version.md"
    - Variable Settings : "variablesettings.md"
    - Login : 
      - Register : "login/sign_up.md"
      - Sign In : "login/sign_in.md"
      - Sign In by Google : "login/login_by_google.md"
    - Update :
      - Activation Account : "update/activation.md" 
      - Change Password : "update/changepass.md"
      - Change Phone Number : "update/changephonenumber.md"
    - GetPlus : 
      - Partner Token : "getplus/partnertoken.md"
      - Request OTP : "getplus/requestotp.md"
      - Verify OTP : "getplus/verifyotp.md"
      - Member Profile : "getplus/memberprofile.md"
      - Member Unlink : "getplus/memberunlink.md"
      - Earn Point : "getplus/earnpoint.md"
      - Point Redeem : "getplus/redeempoint.md"
    - History :
      - Coin  : "history/coinhistory.md"
      - Point : "history/pointhistory.md"
      - Point - Coin : "history/pointcoint.md"
    - Location : "location.md"
    - Member :
      - Add Point : "member/addpoint.md"
      - Feedback : "member/feedback.md"
    - Voucher : 
      - Master Voucher : 
        - Location : "voucher/mastervoucher/location.md"
      - Redeem Voucher : "voucher/redemvoucher.md"
      - Voucher List : "voucher/voucher.md" 
     