site_name: UBEATZ
site_url: https://ubeatz.indosoft.co.id
# theme : readthedocs
theme : 
    name : material
    features : 
      - search.suggest
      - search.highlight
      - content.tabs.link
plugins: 
    - search
    
# markdown_extensions:
#     - attr_list
#     - md_in_html
nav:
    - Home : "index.md"
    - Version : "check_version.md"
    - Variable Settings : "variablesettings.md"
    - User : 
      - Login : 
        - Register : "user/login/sign_up.md"
        - Upload Profile Picture : "user/login/uploadprofpic.md"
        - Sign In : "user/login/sign_in.md"
        - Sign In by Google : "user/login/login_by_google.md"
      - Update :
        - Activation Account : "user/update/activation.md" 
        - Change Password : "user/update/changepass.md"
        - Change Phone Number : "user/update/changephonenumber.md"
    - GetPlus : 
      - Partner Token : "getplus/partnertoken.md"
      - Request OTP : "getplus/requestotp.md"
      - Verify OTP : "getplus/verifyotp.md"
      - Member Profile : "getplus/memberprofile.md"
      - Member Unlink : "getplus/memberunlink.md"
      - Earn Point : "getplus/earnpoint.md"
      - Point Redeem : "getplus/redeempoint.md"
    - Member :
      - Add Point : "member/addpoint.md"
      - Feedback : "member/feedback.md"
    - System : 
      - Devices:
        - Devices List : "system/devices/devices.md"
        - Search Item : "system/devices/searchitem.md"
        - Checkin Item : "system/devices/checkinitem.md"
      - Location : "system/location.md"
      - Tools :
        - Tools List : "system/tools/tools.md"
        - Search Tools : "system/tools/searchtools.md"
      - Voucher : 
        - Master Voucher : 
          - Location : "system/voucher/mastervoucher/location.md"
        - Redeem Voucher : "system/voucher/redemvoucher.md"
        - Voucher List : "system/voucher/voucher.md" 
    - History :
      - Coin  : "history/coinhistory.md"
      - Point : "history/pointhistory.md"
      - Point - Coin : "history/pointcoint.md"   