site_name: UBEATZ
site_url: https://ubeatz.indosoft.co.id
# theme : readthedocs
theme : 
    name : material
    features : 
      - search.suggest
      - search.highlight
      - content.tabs.link
plugins: 
    - search
nav:
    - Home : "index.md"
    - Login : 
      - Register : "login/sign_up.md"
      - Sign In : "login/sign_in.md"
      - Sign In by Google : "login/login_by_google.md"
    - Update :
      - Change Password : "update/changepass.md"
      - Change Phone Number : "update/changephonenumber.md"
      - Activation Account : "update/activation.md" 
    - Member :
      - Point Coint : "member/pointcoint.md"
      - Location : "member/location.md"